import React, { Dispatch } from "react";
import { useDispatch } from "react-redux";
import { dialogControl } from "../../store/actions/dialogActions";
import Form from "../../plugin/form";
import DataTable from "../../plugin/dataTable";
import { Button } from "@mui/material";

const columns = [
  {
    id: 184786,
    name: "company",
    label: "Organization",
    field_type: "text",
    fieldLength: 255,
    list_type: "",
    is_detail_link: true,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: false,
    is_search: true,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 181,
    is_relationship_field: false,
  },
  {
    id: 28321,
    name: "first_name",
    label: "First-Name-SGJK",
    field_type: "text",
    fieldLength: 128,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: false,
    is_search: true,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 90,
    is_relationship_field: false,
  },
  {
    id: 28322,
    name: "last_name",
    label: "Last Name",
    field_type: "text",
    fieldLength: 128,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: false,
    is_search: true,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 83,
    is_relationship_field: false,
  },
  {
    id: 28323,
    name: "email",
    label: "Email",
    field_type: "text",
    fieldLength: 128,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: false,
    is_search: true,
    is_click_to_call: false,
    is_email_field: true,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 252,
    is_relationship_field: false,
  },
  {
    id: 28325,
    name: "phone",
    label: "Phone",
    field_type: "text",
    fieldLength: 128,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: false,
    is_search: true,
    is_click_to_call: true,
    is_twilio: true,
    is_ring_central: false,
    is_twilio_sms: true,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: true,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 101,
    is_relationship_field: false,
  },
  {
    id: 28326,
    name: "mobile",
    label: "Mobile",
    field_type: "text",
    fieldLength: 64,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: false,
    is_search: true,
    is_click_to_call: true,
    is_twilio: true,
    is_ring_central: false,
    is_twilio_sms: true,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: true,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 108,
    is_relationship_field: false,
  },
  {
    id: 28309,
    name: "sales_rep",
    label: "Sales rep",
    field_type: "list",
    fieldLength: 128,
    list_type: "user",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: false,
    is_hidden: false,
    is_search: true,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: true,
    isRequired: true,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 122,
    is_relationship_field: false,
  },
  {
    id: 89093,
    name: "header",
    label: "Client Details",
    field_type: "header",
    fieldLength: 0,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28308,
    name: "t_status",
    label: "Status",
    field_type: "list",
    fieldLength: 64,
    list_type: "regular",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: true,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 122428,
    name: "custom_field16",
    label: "Region",
    field_type: "text",
    fieldLength: 4000,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 129455,
    name: "custom_field18",
    label: "Training",
    field_type: "list",
    fieldLength: 128,
    list_type: "regular",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 33074,
    name: "custom_field3",
    label: "GHIN #",
    field_type: "text",
    fieldLength: 255,
    list_type: "regular",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28311,
    name: "source",
    label: "Source",
    field_type: "list",
    fieldLength: 128,
    list_type: "external",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: true,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 182256,
    name: "franchise_id",
    label: "Franchise#",
    field_type: "text",
    fieldLength: 128,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28312,
    name: "t_type",
    label: "Type",
    field_type: "list",
    fieldLength: 128,
    list_type: "regular",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28314,
    name: "country",
    label: "Billing Country",
    field_type: "list",
    fieldLength: 64,
    list_type: "external",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28315,
    name: "state",
    label: "State",
    field_type: "list",
    fieldLength: 64,
    list_type: "external",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28316,
    name: "city",
    label: "Billing City new",
    field_type: "list",
    fieldLength: 128,
    list_type: "external",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28310,
    name: "industry",
    label: "Industry",
    field_type: "list",
    fieldLength: 128,
    list_type: "regular",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28317,
    name: "zip_code",
    label: "Billing Zip Code",
    field_type: "text",
    fieldLength: 32,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28313,
    name: "address1",
    label: "Billing Address",
    field_type: "text",
    fieldLength: 255,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28356,
    name: "custom_field11",
    label: "Position",
    field_type: "text",
    fieldLength: 256,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: true,
    is_twilio: true,
    is_ring_central: false,
    is_twilio_sms: true,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: true,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 31306,
    name: "custom_field2",
    label: "Custom Field2 - Modified",
    field_type: "text",
    fieldLength: 255,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 32101,
    name: "priority",
    label: "Priority",
    field_type: "list",
    fieldLength: 64,
    list_type: "regular",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 35491,
    name: "custom_field10",
    label: "newly added field",
    field_type: "text",
    fieldLength: 255,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28318,
    name: "website",
    label: "Website",
    field_type: "url",
    fieldLength: 128,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 183757,
    name: "custom_field_date4",
    label: "Date",
    field_type: "date",
    fieldLength: 20,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: true,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 71353,
    name: "custom_field_date2",
    label: "Date and Time",
    field_type: "datetime",
    fieldLength: 20,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 86783,
    name: "custom_field13",
    label: "Custom List",
    field_type: "list",
    fieldLength: 255,
    list_type: "regular",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: true,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 86784,
    name: "custom_field14",
    label: "Custom Field14",
    field_type: "list",
    fieldLength: 128,
    list_type: "regular",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 89095,
    name: "custom_field15",
    label: "iPad field",
    field_type: "text",
    fieldLength: 128,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 103327,
    name: "user_list1",
    label: "Account Manager",
    field_type: "list",
    fieldLength: 128,
    list_type: "user",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 179155,
    name: "custom_field17",
    label: "Custom Phone Field",
    field_type: "text",
    fieldLength: 4000,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: true,
    is_twilio: true,
    is_ring_central: false,
    is_twilio_sms: true,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: true,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 187375,
    name: "custom_field_int2",
    label: "Custom Integer2",
    field_type: "integer",
    fieldLength: 10,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 181723,
    name: "custom_field19",
    label: "Revenue",
    field_type: "list",
    fieldLength: 128,
    list_type: "regular",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 31808,
    name: "job_title",
    label: "Title List",
    field_type: "text",
    fieldLength: 128,
    list_type: "regular",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 187187,
    name: "custom_field_int1",
    label: "Integer Required",
    field_type: "integer",
    fieldLength: 18,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: true,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 172869,
    name: "custom_field_int3",
    label: "Integer Not required",
    field_type: "integer",
    fieldLength: 10,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 129272,
    name: "custom_field_float2",
    label: "Float Not Required",
    field_type: "float",
    fieldLength: 26,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 187108,
    name: "custom_field_float3",
    label: "Float Required",
    field_type: "float",
    fieldLength: 26,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: true,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 89096,
    name: "header",
    label: "Personal information",
    field_type: "header",
    fieldLength: 0,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 129280,
    name: "custom_field27",
    label: "Custom Phone",
    field_type: "text",
    fieldLength: 64,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: true,
    is_twilio: true,
    is_ring_central: false,
    is_twilio_sms: true,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: true,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 44611,
    name: "address2",
    label: "Shipping Address",
    field_type: "text",
    fieldLength: 164,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 81795,
    name: "custom_field12",
    label: "Multi Selection List",
    field_type: "list",
    fieldLength: 128,

    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: true,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 192809,
    name: "custom_field_date6",
    label: "Date field - Sharda Testing",
    field_type: "date",
    fieldLength: 20,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 37929,
    name: "comments",
    label: "Comments",
    field_type: "memo",
    fieldLength: 2048,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 89097,
    name: "header",
    label: "Contact Information",
    field_type: "header",
    fieldLength: 0,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 44610,
    name: "salutation",
    label:
      "Title test title test Title test title test Title test title test  title test  title test",
    field_type: "text",
    fieldLength: 32,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 44612,
    name: "custom_field8",
    label: "Middle Name",
    field_type: "text",
    fieldLength: 128,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 34949,
    name: "custom_field6",
    label: "Suffix",
    field_type: "text",
    fieldLength: 128,
    list_type: "regular",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 65293,
    name: "custom_field40",
    label: "Spouse",
    field_type: "list",
    fieldLength: 32,
    list_type: "regular",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 44609,
    name: "custom_field7",
    label: "Contact ID",
    field_type: "text",
    fieldLength: 255,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28324,
    name: "email2",
    label: "Other email",
    field_type: "text",
    fieldLength: 128,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: true,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 31041,
    name: "custom_field1",
    label: "Domain",
    field_type: "text",
    fieldLength: 255,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 33072,
    name: "custom_field4",
    label: "NCGA Member",
    field_type: "text",
    fieldLength: 256,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 35647,
    name: "custom_field_url1",
    label: "Linked in",
    field_type: "url",
    fieldLength: 128,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 45089,
    name: "custom_field_date1",
    label: "Custom Date Plus",
    field_type: "date",
    fieldLength: 20,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: true,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 45329,
    name: "custom_field_float1",
    label: "Custom Float'1",
    field_type: "float",
    fieldLength: 26,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 65675,
    name: "custom_field9",
    label: "Language",
    field_type: "list",
    fieldLength: 255,
    list_type: "regular",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: true,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 65676,
    name: "custom_field_date3",
    label: "Contact Expiration Contact Expiration",
    field_type: "date",
    fieldLength: 20,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 186854,
    name: "custom_field45",
    label: "Preliminary Customer Number",
    field_type: "text",
    fieldLength: 128,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 41869,
    name: "custom_field44",
    label: "Custom Field44",
    field_type: "text",
    fieldLength: 16,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 89098,
    name: "",
    label: "",
    field_type: "",
    fieldLength: 0,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 89099,
    name: "header",
    label: "Additional Information",
    field_type: "header",
    fieldLength: 0,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28341,
    name: "t_creater",
    label: "Created by",
    field_type: "text",
    fieldLength: 128,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: true,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28342,
    name: "created_on",
    label: "Created on",
    field_type: "datetime",
    fieldLength: 20,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: true,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28343,
    name: "update_by",
    label: "Updated by",
    field_type: "text",
    fieldLength: 128,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: true,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28344,
    name: "updated_on",
    label: "Updated on",
    field_type: "datetime",
    fieldLength: 20,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: true,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 28345,
    name: "visible_to",
    label: "Visible to",
    field_type: "text",
    fieldLength: 255,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: true,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 31036,
    name: "ol_sync",
    label: "Outlook Sync",
    field_type: "list",
    fieldLength: 16,
    list_type: "regular",
    is_detail_link: false,
    is_group_by: true,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 79766,
    name: "workflow_name",
    label: "Workflow Name",
    field_type: "list",
    fieldLength: 255,
    list_type: "regular",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 167353,
    name: "custom_field_date5",
    label: "Custom Date time",
    field_type: "datetime",
    fieldLength: 20,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 47908,
    name: "workflow_id",
    label: "Workflow Id",
    field_type: "integer",
    fieldLength: 10,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 113156,
    name: "lead_score",
    label: "Lead Score",
    field_type: "integer",
    fieldLength: 5,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 185657,
    name: "opportunity_amount",
    label: "Accounts Opportunity $",
    field_type: "float",
    fieldLength: 26,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: true,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 190477,
    name: "royalty_percent",
    label: "Royalty %",
    field_type: "float",
    fieldLength: 26,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: true,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 191428,
    name: "billto",
    label: "Bill To",
    field_type: "memo",
    fieldLength: 1000,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 191483,
    name: "shipto",
    label: "Ship To",
    field_type: "memo",
    fieldLength: 1000,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 194389,
    name: "probability",
    label: "Probability %",
    field_type: "text",
    fieldLength: 64,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 194464,
    name: "forecast_amount",
    label: "Forecast $",
    field_type: "float",
    fieldLength: 26,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: true,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 194539,
    name: "close_date",
    label: "Close date",
    field_type: "date",
    fieldLength: 20,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 195369,
    name: "custom_field_date9",
    label: "Expected Open Date",
    field_type: "date",
    fieldLength: 20,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 196497,
    name: "main_contact_id",
    label: "Main Contact Id",
    field_type: "integer",
    fieldLength: 11,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 196499,
    name: "main_contact_id",
    label: "Main Contact Id",
    field_type: "integer",
    fieldLength: 11,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 196503,
    name: "main_contact_id",
    label: "Main Contact Id",
    field_type: "integer",
    fieldLength: 11,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 196584,
    name: "main_contact_id",
    label: "Main Contact Id",
    field_type: "integer",
    fieldLength: 11,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 196665,
    name: "main_contact_id",
    label: "Main Contact Id",
    field_type: "integer",
    fieldLength: 11,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 197013,
    name: "main_contact_id",
    label: "Main Contact Id",
    field_type: "integer",
    fieldLength: 11,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 197098,
    name: "main_contact_id",
    label: "Main Contact Id",
    field_type: "integer",
    fieldLength: 11,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
  {
    id: 197357,
    name: "main_contact_id",
    label: "Main Contact Id",
    field_type: "integer",
    fieldLength: 11,
    list_type: "",
    is_detail_link: false,
    is_group_by: false,
    is_inline_edit: false,
    is_hidden: true,
    is_search: false,
    is_click_to_call: false,
    is_email_field: false,
    is_currency_field: false,
    is_sales_rep: false,
    isRequired: false,
    is_phone_field: false,
    is_lookup_field: false,
    lookup_table_id: 0,
    lookup_field_id: 0,
    width: 0,
    is_relationship_field: false,
  },
];

const rows = [
  {
    id: 4556535,
    company: "yhytrhytr",
    first_name: "",
    last_name: "rgegrthtyh",
    email: "",
    phone: "",
    mobile: "",
    sales_rep: "Test User12",
    show_pic_url: "",
  },
  {
    id: 4541975,
    company: "Sterillium LLC",
    first_name: "Sterillium",
    last_name: "",
    email: "engineering@soffrontcrm.com",
    phone: "987-422-3340",
    mobile: "987-422-3340",
    sales_rep: "Dev User",
    show_pic_url:
      "https://s3.amazonaws.com/snapshotcrm.test/k893_205389?date=1685347801311",
  },
  {
    id: 4556663,
    company: "SF Account Without Style",
    first_name: "Acount Without Style",
    last_name: "",
    email: "without@noemail.com",
    phone: "",
    mobile: "",
    sales_rep: "Dev User",
    show_pic_url: "",
  },
  {
    id: 4556662,
    company: "SF Account With Style",
    first_name: "Account With Style",
    last_name: "",
    email: "acount@noemail.com",
    phone: "",
    mobile: "",
    sales_rep: "Review User",
    show_pic_url: "",
  },
  {
    id: 4554168,
    company: "SF",
    first_name: "Tapas",
    last_name: "Bhatta",
    email: "tapas.bhatta@soffrontcrm.com",
    phone: "",
    mobile: "862-080-5893",
    sales_rep: "Indranil Patra",
    show_pic_url: "",
  },
  {
    id: 4492487,
    company: "Priyanka Soff",
    first_name: "",
    last_name: "",
    email: "priyanka.das@soffrontcrm.com",
    phone: "",
    mobile: "",
    sales_rep: "Indranil Patra",
    show_pic_url: "",
  },
  {
    id: 461338,
    company: "Metal Housing Company",
    first_name: "Monica",
    last_name: "3137",
    email: "testsoffront@soffrontcrm.com",
    phone: "8989899898",
    mobile: "",
    sales_rep: "Dipanjan Banik",
    show_pic_url: "",
  },
  {
    id: 430979,
    company: "MAC-MINI",
    first_name: "Raja",
    last_name: "Pat",
    email: "indranil.patra@soffrontcrm.com",
    phone: "891-032-7459",
    mobile: "700-332-5448",
    sales_rep: "IndranilforU",
    show_pic_url:
      "https://s3.amazonaws.com/snapshotcrm.test/k893_197308?date=1685347801312",
  },
  {
    id: 4547449,
    company: "Lucky Group - Ambala",
    first_name: "Mansher",
    last_name: "Sing",
    email: "lucky.sathe@noemail.com",
    phone: "987-422-3340",
    mobile: "891-032-7460",
    sales_rep: "Indranil Patra",
    show_pic_url: "",
  },
  {
    id: 607553,
    company: "Engineering & Inc.",
    first_name: "",
    last_name: "Engineering",
    email: "engineering@soffrontcrm.com",
    phone: "700-332-5448",
    mobile: "983-175-9557",
    sales_rep: "Dipanjan Banik",
    show_pic_url: "",
  },
  {
    id: 4556546,
    company: "Change Sales Rep",
    first_name: "",
    last_name: "Change Sales Rep",
    email: "",
    phone: "",
    mobile: "",
    sales_rep: "Dev User",
    show_pic_url: "",
  },
  {
    id: 4547448,
    company: "alexander  ferguson",
    first_name: "alexander",
    last_name: "ferguson",
    email: "babai.bandyopadhyayQA@gmail.com",
    phone: "741-852-9636",
    mobile: "852-963-7415",
    sales_rep: "Indranil4U",
    show_pic_url: "",
  },
  {
    id: 4494666,
    company: "30th August 2019 Test Company",
    first_name: "mihir",
    last_name: "das",
    email: "mihir@nomail.com",
    phone: "033-254-7895",
    mobile: "900-729-2008",
    sales_rep: "Indranil Patra",
    show_pic_url: "",
  },
  {
    id: 4556483,
    company: "24th Mar 2022",
    first_name: "",
    last_name: "",
    email: "24thmar@noemail.com",
    phone: "",
    mobile: "",
    sales_rep: "Dev User",
    show_pic_url: "",
  },
  {
    id: 4068280,
    company: "21st Sep After Build",
    first_name: "qsa",
    last_name: "Indranil",
    email: "nibedita.sahoo@soffrontcrm.com",
    phone: "",
    mobile: "",
    sales_rep: "Dipanjan Banik",
    show_pic_url: "",
  },
  {
    id: 4495063,
    company: "20th Dec 2019 Organization",
    first_name: "Toma",
    last_name: "Curran",
    email: "arindamg.soffront@gmail.com",
    phone: "900-729-2008",
    mobile: "03324225072",
    sales_rep: "Indranil Patra",
    show_pic_url: "",
  },
  {
    id: 4547582,
    company: "19th June 2021 Unit",
    first_name: "19th June",
    last_name: "2021",
    email: "19thjune@company.com",
    phone: "700-332-5448",
    mobile: "",
    sales_rep: "Indranil Patra",
    show_pic_url: "",
  },
  {
    id: 4568366,
    company: "17th May 2023",
    first_name: "",
    last_name: "17th May 2023",
    email: "test@soffront.com",
    phone: "",
    mobile: "",
    sales_rep: "Indranil Patra",
    show_pic_url: "",
  },
  {
    id: 3950508,
    company: "17th July 2017-1",
    first_name: "Anup",
    last_name: "",
    email: "anup.saha@soffrontcrm.com",
    phone: "",
    mobile: "",
    sales_rep: "Indranil Patra",
    show_pic_url: "",
  },
  {
    id: 4494778,
    company: "16th Sept 2019 Test Company",
    first_name: "",
    last_name: "Saha",
    email: "santu.b@soffrontcrm.com",
    phone: "",
    mobile: "",
    sales_rep: "Indranil Patra",
    show_pic_url: "",
  },
  {
    id: 4556020,
    company: "",
    first_name: "",
    last_name: "",
    email: "",
    phone: "",
    mobile: "",
    sales_rep: "Dev User",
    show_pic_url: "",
  },
  {
    id: 4564969,
    company: "",
    first_name: "test",
    last_name: "",
    email: "sdf@et.sdf",
    phone: "46457547",
    mobile: "",
    sales_rep: "Indranil Patra",
    show_pic_url: "",
  },
  {
    id: 4556021,
    company: "",
    first_name: "",
    last_name: "",
    email: "",
    phone: "",
    mobile: "",
    sales_rep: "Dev User",
    show_pic_url: "",
  },
  {
    id: 4547418,
    company: "",
    first_name: "",
    last_name: "",
    email: "",
    phone: "",
    mobile: "",
    sales_rep: "Dev User",
    show_pic_url: "",
  },
];

interface dispatchFunction {
  type: string;
  payload: any;
}
const RedirectComponent: React.FC = () => {
  const dispatch: Dispatch<dispatchFunction> = useDispatch();
  const open = () => {
    // dispatch(drawerControl('hi','alert',{},true,true,'100%'));
    dispatch(dialogControl("hi", "alert", null, true, false));
  };
  return (
    <>
      <Form FormData={[]} />
      <DataTable columns={columns} rows={rows} selectionKey="name" />
      <Button onClick={() => open()}>hii</Button>
    </>
  );
};

export default RedirectComponent;
