const data = {
    userMenu: [
      {
        open: false,
        accessible: true,
        label: "Dashboard",
        name: "dashboard",
        type: "link",
        imageName: "DashboardTwoTone",
        subItems: [],
      },
      {
        open: false,
        accessible: true,
        label: "Knowledge Bases",
        name: "knowledgeBases",
        type: "link",
        imageName: "NewspaperTwoTone",
        homeName: "knowledgeBases",
        subItems: [
          {
            open: false,
            accessible: true,
            label: "Posts",
            name: "posts",
            type: "link",
            imageName: "ReceiptTwoTone",
            homeName: "knowledgeBases",
          },
          {
            open: false,
            accessible: true,
            label: "Category",
            name: "category",
            type: "link",
            imageName: "FilePresentTwoTone",
            homeName: "knowledgeBases",
          }
        ],
      },
      {
        open: false,
        accessible: true,
        label: "FAQ",
        name: "faq",
        type: "link",
        imageName: "QuizTwoTone",
        homeName: "faq",
        subItems: [
          {
            open: false,
            accessible: true,
            label: "FAQs",
            name: "faqs",
            type: "link",
            imageName: "LiveHelpTwoTone",
            homeName: "faq",
          },
          {
            open: false,
            accessible: true,
            label: "Category",
            name: "faqCategory",
            type: "link",
            imageName: "ClassTwoTone",
            homeName: "faq",
          }
        ],
      },
      {
        open: false,
        accessible: true,
        label: "Departments",
        name: "departments",
        type: "link",
        imageName: "AccountTreeTwoTone",
        homeName: "departments",
        subItems: [],
      },
      {
        open: false,
        accessible: true,
        label: "Priority of",
        name: "priority",
        type: "link",
        imageName: "KeyboardDoubleArrowUpTwoTone",
        homeName: "priority",
        subItems: [],
      },
      {
        open: false,
        accessible: true,
        label: "Tickets",
        name: "tickets",
        type: "link",
        imageName: "ConfirmationNumberTwoTone",
        homeName: "tickets",
        subItems: [],
      },
      {
        open: false,
        accessible: true,
        label: "Customers",
        name: "customers",
        type: "link",
        imageName: "GroupTwoTone",
        homeName: "customers",
        subItems: [],
      },
      {
        open: false,
        accessible: true,
        label: "Users",
        name: "user",
        type: "link",
        imageName: "ManageAccountsTwoTone",
        homeName: "user",
        subItems: [
          {
            open: false,
            accessible: true,
            label: "Users",
            name: "users",
            type: "link",
            imageName: "SupportAgentTwoTone",
            homeName: "user",
          },
          {
            open: false,
            accessible: true,
            label: "Roles",
            name: "roles",
            type: "link",
            imageName: "SettingsAccessibilityTwoTone",
            homeName: "user",
          }
        ],
      },
    ],
    columns:{
      category:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 184786,
          name: "name",
          label: "Name",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
      ],
      posts:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 184786,
          name: "title",
          label: "Title",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 184786,
          name: "category",
          label: "Category",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 184786,
          name: "status",
          label: "Status",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
      ],
      departments:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 184786,
          name: "name",
          label: "Name",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
      ],
      faqCategory:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 184786,
          name: "name",
          label: "Name",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
      ],
      faqs:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 184786,
          name: "question",
          label: "Question",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 184786,
          name: "answer",
          label: "Answer",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 184786,
          name: "category",
          label: "Category",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
      ],
      priority:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 184786,
          name: "title",
          label: "Title",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
      ],
      tickets: [
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 184786,
          name: "title",
          label: "Title",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 184786,
          name: "customer",
          label: "Customer",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 184786,
          name: "assigned",
          label: "Assigned",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 184786,
          name: "deperment",
          label: "Deperment",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 184786,
          name: "priority",
          label: "Priority",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 184786,
          name: "status",
          label: "Status",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
      ],
      customers:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 184786,
          name: "name",
          label: "Name",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 184786,
          name: "email",
          label: "Email",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
      ],
      roles:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 184786,
          name: "name",
          label: "Name",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        }
      ],
      users:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 184786,
          name: "name",
          label: "Name",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 184786,
          name: "email",
          label: "Email",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 184786,
          name: "role",
          label: "Role",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
      ],
    },
    form:{
      category:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: true,
          grid: 12,
        },
        {
          id: 184786,
          name: "name",
          label: "Name",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
      ],
      posts:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: true,
          grid: 12,
        },
        {
          id: 184786,
          name: "title",
          label: "Title",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 184786,
          name: "category",
          label: "Category",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 184786,
          name: "status",
          label: "Status",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
      ],
      departments:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: true,
          grid: 12,
        },
        {
          id: 184786,
          name: "name",
          label: "Name",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
      ],
      faqCategory:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: true,
          grid: 12,
        },
        {
          id: 184786,
          name: "name",
          label: "Name",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
      ],
      faqs:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: true,
          grid: 12,
        },
        {
          id: 184786,
          name: "question",
          label: "Question",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 184786,
          name: "answer",
          label: "Answer",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 184786,
          name: "category",
          label: "Category",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
      ],
      priority:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: true,
          grid: 12,
        },
        {
          id: 184786,
          name: "name",
          label: "Name",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
      ],
      tickets: [
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: true,
          grid: 12,
        },
        {
          id: 184786,
          name: "title",
          label: "Title",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 184786,
          name: "customer",
          label: "Customer",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 184786,
          name: "assigned",
          label: "Assigned",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 184786,
          name: "deperment",
          label: "Deperment",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 184786,
          name: "priority",
          label: "Priority",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 184786,
          name: "status",
          label: "Status",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        }
      ],
      customer:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: true,
          grid: 12,
        },
        {
          id: 184786,
          name: "name",
          label: "Name",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 184786,
          name: "email",
          label: "Email",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
      ],
      roles:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: true,
          grid: 12,
        },
        {
          id: 184786,
          name: "name",
          label: "Name",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        }
      ],
      users:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: true,
          grid: 12,
        },
        {
          id: 184786,
          name: "name",
          label: "Name",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 184786,
          name: "email",
          label: "Email",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 184786,
          name: "role",
          label: "Role",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
      ],
    },
    rows: [
      {
        id: 4556535,
        company: "yhytrhytr",
        first_name: "",
        last_name: "rgegrthtyh",
        email: "",
        phone: "",
        mobile: "",
        sales_rep: "Test User12",
        show_pic_url: "",
      },
      {
        id: 4541975,
        company: "Sterillium LLC",
        first_name: "Sterillium",
        last_name: "",
        email: "engineering@soffrontcrm.com",
        phone: "987-422-3340",
        mobile: "987-422-3340",
        sales_rep: "Dev User",
        show_pic_url:
          "https://s3.amazonaws.com/snapshotcrm.test/k893_205389?date=1685347801311",
      },
      {
        id: 4556663,
        company: "SF Account Without Style",
        first_name: "Acount Without Style",
        last_name: "",
        email: "without@noemail.com",
        phone: "",
        mobile: "",
        sales_rep: "Dev User",
        show_pic_url: "",
      },
      {
        id: 4556662,
        company: "SF Account With Style",
        first_name: "Account With Style",
        last_name: "",
        email: "acount@noemail.com",
        phone: "",
        mobile: "",
        sales_rep: "Review User",
        show_pic_url: "",
      },
      {
        id: 4554168,
        company: "SF",
        first_name: "Tapas",
        last_name: "Bhatta",
        email: "tapas.bhatta@soffrontcrm.com",
        phone: "",
        mobile: "862-080-5893",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 4492487,
        company: "Priyanka Soff",
        first_name: "",
        last_name: "",
        email: "priyanka.das@soffrontcrm.com",
        phone: "",
        mobile: "",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 461338,
        company: "Metal Housing Company",
        first_name: "Monica",
        last_name: "3137",
        email: "testsoffront@soffrontcrm.com",
        phone: "8989899898",
        mobile: "",
        sales_rep: "Dipanjan Banik",
        show_pic_url: "",
      },
      {
        id: 430979,
        company: "MAC-MINI",
        first_name: "Raja",
        last_name: "Pat",
        email: "indranil.patra@soffrontcrm.com",
        phone: "891-032-7459",
        mobile: "700-332-5448",
        sales_rep: "IndranilforU",
        show_pic_url:
          "https://s3.amazonaws.com/snapshotcrm.test/k893_197308?date=1685347801312",
      },
      {
        id: 4547449,
        company: "Lucky Group - Ambala",
        first_name: "Mansher",
        last_name: "Sing",
        email: "lucky.sathe@noemail.com",
        phone: "987-422-3340",
        mobile: "891-032-7460",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 607553,
        company: "Engineering & Inc.",
        first_name: "",
        last_name: "Engineering",
        email: "engineering@soffrontcrm.com",
        phone: "700-332-5448",
        mobile: "983-175-9557",
        sales_rep: "Dipanjan Banik",
        show_pic_url: "",
      },
      {
        id: 4556546,
        company: "Change Sales Rep",
        first_name: "",
        last_name: "Change Sales Rep",
        email: "",
        phone: "",
        mobile: "",
        sales_rep: "Dev User",
        show_pic_url: "",
      },
      {
        id: 4547448,
        company: "alexander  ferguson",
        first_name: "alexander",
        last_name: "ferguson",
        email: "babai.bandyopadhyayQA@gmail.com",
        phone: "741-852-9636",
        mobile: "852-963-7415",
        sales_rep: "Indranil4U",
        show_pic_url: "",
      },
      {
        id: 4494666,
        company: "30th August 2019 Test Company",
        first_name: "mihir",
        last_name: "das",
        email: "mihir@nomail.com",
        phone: "033-254-7895",
        mobile: "900-729-2008",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 4556483,
        company: "24th Mar 2022",
        first_name: "",
        last_name: "",
        email: "24thmar@noemail.com",
        phone: "",
        mobile: "",
        sales_rep: "Dev User",
        show_pic_url: "",
      },
      {
        id: 4068280,
        company: "21st Sep After Build",
        first_name: "qsa",
        last_name: "Indranil",
        email: "nibedita.sahoo@soffrontcrm.com",
        phone: "",
        mobile: "",
        sales_rep: "Dipanjan Banik",
        show_pic_url: "",
      },
      {
        id: 4495063,
        company: "20th Dec 2019 Organization",
        first_name: "Toma",
        last_name: "Curran",
        email: "arindamg.soffront@gmail.com",
        phone: "900-729-2008",
        mobile: "03324225072",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 4547582,
        company: "19th June 2021 Unit",
        first_name: "19th June",
        last_name: "2021",
        email: "19thjune@company.com",
        phone: "700-332-5448",
        mobile: "",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 4568366,
        company: "17th May 2023",
        first_name: "",
        last_name: "17th May 2023",
        email: "test@soffront.com",
        phone: "",
        mobile: "",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 3950508,
        company: "17th July 2017-1",
        first_name: "Anup",
        last_name: "",
        email: "anup.saha@soffrontcrm.com",
        phone: "",
        mobile: "",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 4494778,
        company: "16th Sept 2019 Test Company",
        first_name: "",
        last_name: "Saha",
        email: "santu.b@soffrontcrm.com",
        phone: "",
        mobile: "",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 4556020,
        company: "",
        first_name: "",
        last_name: "",
        email: "",
        phone: "",
        mobile: "",
        sales_rep: "Dev User",
        show_pic_url: "",
      },
      {
        id: 4564969,
        company: "",
        first_name: "test",
        last_name: "",
        email: "sdf@et.sdf",
        phone: "46457547",
        mobile: "",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 4556021,
        company: "",
        first_name: "",
        last_name: "",
        email: "",
        phone: "",
        mobile: "",
        sales_rep: "Dev User",
        show_pic_url: "",
      },
      {
        id: 4547418,
        company: "",
        first_name: "",
        last_name: "",
        email: "",
        phone: "",
        mobile: "",
        sales_rep: "Dev User",
        show_pic_url: "",
      },
    ],
  };
  export const { userMenu, columns,form, rows } = data;
  