const data = {
    userMenu: [
      {
        open: false,
        accessible: true,
        label: "Dashboard",
        name: "dashboard",
        type: "link",
        imageName: "DashboardTwoTone",
        subItems: [],
      },
      {
        open: false,
        accessible: true,
        label: "My Leads",
        name: "myLeads",
        type: "link",
        imageName: "NewspaperTwoTone",
        homeName: "knowledgeBases",
        subItems: [],
      },
      {
        open: false,
        accessible: true,
        label: "Sales List",
        name: "salesList",
        type: "link",
        imageName: "QuizTwoTone",
        homeName: "faq",
        subItems: [],
      },
      {
        open: false,
        accessible: true,
        label: "Manage User",
        name: "manageUser",
        type: "link",
        imageName: "AccountTreeTwoTone",
        homeName: "user",
        subItems: [
          {
            open: false,
            accessible: true,
            label: "User",
            name: "user",
            type: "link",
            imageName: "SupportAgentTwoTone",
            homeName: "user",
          },
        ],
      },
      {
        open: false,
        accessible: true,
        label: "Report",
        name: "report",
        type: "link",
        imageName: "KeyboardDoubleArrowUpTwoTone",
        homeName: "priority",
        subItems: [
          {
            open: false,
            accessible: true,
            label: "Sales Report",
            name: "salesReport",
            type: "link",
            imageName: "SupportAgentTwoTone",
            homeName: "priority",
          },
        ],
      },
      
      {
        open: false,
        accessible: true,
        label: "Settings",
        name: "settings",
        type: "link",
        imageName: "ManageAccountsTwoTone",
        homeName: "user",
        subItems: [
          {
            open: false,
            accessible: true,
            label: "Reset Password",
            name: "resetPassword",
            type: "link",
            imageName: "SupportAgentTwoTone",
            homeName: "user",
          },
          
        ],
      },
    ],
    columns:{
      myLeads:[
        {
          id: 1,
          name: "siNo",
          label: "Si.No",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 2,
          name: "date",
          label: "Date",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 3,
          name: "time",
          label: "Time",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 4,
          name: "name",
          label: "Name",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 5,
          name: "phone",
          label: "Phone",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 6,
          name: "state",
          label: "State",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 7,
          name: "assign",
          label: "Assign",
          type: "action",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 8,
          name: "service",
          label: "Service",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },

        {
          id: 9,
          name: "remarks",
          label: "Remarks",
          type: "action",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },        

      ],
      salesList:[
        {
          id: 10,
          name: "siNo",
          label: "Si.No",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 11,
          name: "date",
          label: "Date",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 12,
          name: "name",
          label: "Name",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 13,
          name: "phone",
          label: "Phone",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 14,
          name: "email",
          label: "Email",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 15,
          name: "service",
          label: "Service",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 16,
          name: "amount",
          label: "Amount",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 17,
          name: "assign",
          label: "Assign",
          type: "action",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 18,
          name: "status",
          label: "Status",
          type: "action",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 19,
          name: "salesExecutive",
          label: "Sales Executive",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },

        {
          id: 16,
          name: "amount",
          label: "Amount",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },{
          id: 20,
          name: "modify",
          label: "Modify",
          type: "action",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },    
        {
          id: 21,
          name: "delete",
          label: "Delete",
          type: "action",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },      

      ],
      salesReport:[
        {
          id: 101,
          name: "siNo",
          label: "Si.No",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 102,
          name: "name",
          label: "Name",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 103,
          name: "email",
          label: "Email",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },{
          id: 104,
          name: "phone",
          label: "Phone",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 105,
          name: "state",
          label: "State",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },

        {
          id: 106,
          name: "service",
          label: "Service",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },

      ],
      user:[
        {
          id: 24,
          name: "slNo",
          label: "Si No",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: true,
          width: 181,
        },
        {
          id: 25,
          name: "userName",
          label: "Username",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 26,
          name: "password",
          label: "Password",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 27,
          name: "userType",
          label: "User Type",
          type: "text",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 28,
          name: "action",
          label: "Action",
          type: "action",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
        {
          id: 29,
          name: "status",
          label: "Status",
          type: "action",
          isShortable: true,
          isFilterable: true,
          iaActionField: false,
          width: 181,
        },
      ],
    },
    form:{
      salesList:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: true,
          grid: 12,
        },
        {
          id: 2323,
          name: "purchaseDate",
          label: "Purchase Date",
          type: "date",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 184786,
          name: "name",
          label: "Name",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 343,
          name: "email",
          label: "Email",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 232,
          name: "phone",
          label: "Phone",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 342,
          name: "service",
          label: "Service",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 325,
          name: "amount",
          label: "Amount",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 325,
          name: "salesExecutive",
          label: "Sales Executive",
          type: "select",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          optionList:[1,2, 3],
          grid: 12,
        },
        
      ],
      user:[
        {
          id: 184786,
          name: "id",
          label: "Id",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: true,
          grid: 12,
        },
        {
          id: 18486,
          name: "name",
          label: "Full Name",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 18786,
          name: "username",
          label: "Username",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 18476,
          name: "password",
          label: "Password",
          type: "text",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 176,
          name: "givePermission",
          label: "Give Permission",
          type: "header",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1760,
          name: "trademarkObjection",
          label: "Trademark Objection",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1761,
          name: "trademarkOpposition",
          label: "Trademark Opposition",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1762,
          name: "trademarkHearing",
          label: "Trademark Hearing",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1763,
          name: "copyright",
          label: "Copyright",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1764,
          name: "privateLimitedCompany",
          label: "Private Limited Company",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1765,
          name: "llpRegistration",
          label: "LLP Registration",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1766,
          name: "onePersonCompany",
          label: "One Person Company",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1767,
          name: "sectionCompany",
          label: "Section 8 Company",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1768,
          name: "gstRegistration",
          label: "GST Registration",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1769,
          name: "isoRegistration",
          label: "ISO Certifications",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1770,
          name: "importExportCode",
          label: "Import Export Code",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1771,
          name: "gstReturnFilling",
          label: "GST Return Filing",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1772,
          name: "onlineIncomeTaxReturnFilling",
          label: "Income tax return filing online",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1773,
          name: "trademarkRegistration",
          label: "Trademark Registration",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1774,
          name: "fssaiRegistration",
          label: "Fssai Registration",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },
        {
          id: 1775,
          name: "fssaiReturnFiling",
          label: "FSSAI Return Filing",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        }, {
          id: 1776,
          name: "fssaiRenewal",
          label: "FSSAI Renewal",
          type: "check-box",
          isRequired: true,
          isFilterable: true,
          isHidden: false,
          grid: 12,
        },



        {
          id: 1847,
          name: "usertype",
          label: "User Type",
          type: "select",
          isRequired: true,
          isFilterable: true,
          optionList:['Super Admin','Vendor', 'Tele Caller', 'Filling'],
          isHidden: false,
          grid: 12,
        },
      ],
      searchLeads:[
        {
          id: 165,
          name: "startDate",
          label: "Start Date",
          type: "date",
          isRequired: true,
          isFilterable: true,
          isHidden: true,
          grid: 12,
        },{
          id: 166,
          name: "endDate",
          label: "End Date",
          type: "date",
          isRequired: true,
          isFilterable: true,
          isHidden: true,
          grid: 12,
        },

      ],
    },
    rows: [
      {
        id: 4556535,
        company: "yhytrhytr",
        first_name: "",
        last_name: "rgegrthtyh",
        email: "",
        phone: "",
        mobile: "",
        sales_rep: "Test User12",
        show_pic_url: "",
      },
      {
        id: 4541975,
        company: "Sterillium LLC",
        first_name: "Sterillium",
        last_name: "",
        email: "engineering@soffrontcrm.com",
        phone: "987-422-3340",
        mobile: "987-422-3340",
        sales_rep: "Dev User",
        show_pic_url:
          "https://s3.amazonaws.com/snapshotcrm.test/k893_205389?date=1685347801311",
      },
      {
        id: 4556663,
        company: "SF Account Without Style",
        first_name: "Acount Without Style",
        last_name: "",
        email: "without@noemail.com",
        phone: "",
        mobile: "",
        sales_rep: "Dev User",
        show_pic_url: "",
      },
      {
        id: 4556662,
        company: "SF Account With Style",
        first_name: "Account With Style",
        last_name: "",
        email: "acount@noemail.com",
        phone: "",
        mobile: "",
        sales_rep: "Review User",
        show_pic_url: "",
      },
      {
        id: 4554168,
        company: "SF",
        first_name: "Tapas",
        last_name: "Bhatta",
        email: "tapas.bhatta@soffrontcrm.com",
        phone: "",
        mobile: "862-080-5893",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 4492487,
        company: "Priyanka Soff",
        first_name: "",
        last_name: "",
        email: "priyanka.das@soffrontcrm.com",
        phone: "",
        mobile: "",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 461338,
        company: "Metal Housing Company",
        first_name: "Monica",
        last_name: "3137",
        email: "testsoffront@soffrontcrm.com",
        phone: "8989899898",
        mobile: "",
        sales_rep: "Dipanjan Banik",
        show_pic_url: "",
      },
      {
        id: 430979,
        company: "MAC-MINI",
        first_name: "Raja",
        last_name: "Pat",
        email: "indranil.patra@soffrontcrm.com",
        phone: "891-032-7459",
        mobile: "700-332-5448",
        sales_rep: "IndranilforU",
        show_pic_url:
          "https://s3.amazonaws.com/snapshotcrm.test/k893_197308?date=1685347801312",
      },
      {
        id: 4547449,
        company: "Lucky Group - Ambala",
        first_name: "Mansher",
        last_name: "Sing",
        email: "lucky.sathe@noemail.com",
        phone: "987-422-3340",
        mobile: "891-032-7460",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 607553,
        company: "Engineering & Inc.",
        first_name: "",
        last_name: "Engineering",
        email: "engineering@soffrontcrm.com",
        phone: "700-332-5448",
        mobile: "983-175-9557",
        sales_rep: "Dipanjan Banik",
        show_pic_url: "",
      },
      {
        id: 4556546,
        company: "Change Sales Rep",
        first_name: "",
        last_name: "Change Sales Rep",
        email: "",
        phone: "",
        mobile: "",
        sales_rep: "Dev User",
        show_pic_url: "",
      },
      {
        id: 4547448,
        company: "alexander  ferguson",
        first_name: "alexander",
        last_name: "ferguson",
        email: "babai.bandyopadhyayQA@gmail.com",
        phone: "741-852-9636",
        mobile: "852-963-7415",
        sales_rep: "Indranil4U",
        show_pic_url: "",
      },
      {
        id: 4494666,
        company: "30th August 2019 Test Company",
        first_name: "mihir",
        last_name: "das",
        email: "mihir@nomail.com",
        phone: "033-254-7895",
        mobile: "900-729-2008",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 4556483,
        company: "24th Mar 2022",
        first_name: "",
        last_name: "",
        email: "24thmar@noemail.com",
        phone: "",
        mobile: "",
        sales_rep: "Dev User",
        show_pic_url: "",
      },
      {
        id: 4068280,
        company: "21st Sep After Build",
        first_name: "qsa",
        last_name: "Indranil",
        email: "nibedita.sahoo@soffrontcrm.com",
        phone: "",
        mobile: "",
        sales_rep: "Dipanjan Banik",
        show_pic_url: "",
      },
      {
        id: 4495063,
        company: "20th Dec 2019 Organization",
        first_name: "Toma",
        last_name: "Curran",
        email: "arindamg.soffront@gmail.com",
        phone: "900-729-2008",
        mobile: "03324225072",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 4547582,
        company: "19th June 2021 Unit",
        first_name: "19th June",
        last_name: "2021",
        email: "19thjune@company.com",
        phone: "700-332-5448",
        mobile: "",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 4568366,
        company: "17th May 2023",
        first_name: "",
        last_name: "17th May 2023",
        email: "test@soffront.com",
        phone: "",
        mobile: "",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 3950508,
        company: "17th July 2017-1",
        first_name: "Anup",
        last_name: "",
        email: "anup.saha@soffrontcrm.com",
        phone: "",
        mobile: "",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 4494778,
        company: "16th Sept 2019 Test Company",
        first_name: "",
        last_name: "Saha",
        email: "santu.b@soffrontcrm.com",
        phone: "",
        mobile: "",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 4556020,
        company: "",
        first_name: "",
        last_name: "",
        email: "",
        phone: "",
        mobile: "",
        sales_rep: "Dev User",
        show_pic_url: "",
      },
      {
        id: 4564969,
        company: "",
        first_name: "test",
        last_name: "",
        email: "sdf@et.sdf",
        phone: "46457547",
        mobile: "",
        sales_rep: "Indranil Patra",
        show_pic_url: "",
      },
      {
        id: 4556021,
        company: "",
        first_name: "",
        last_name: "",
        email: "",
        phone: "",
        mobile: "",
        sales_rep: "Dev User",
        show_pic_url: "",
      },
      {
        id: 4547418,
        company: "",
        first_name: "",
        last_name: "",
        email: "",
        phone: "",
        mobile: "",
        sales_rep: "Dev User",
        show_pic_url: "",
      },
    ],
  };
  export const { userMenu, columns,form, rows } = data;
  