const globalConst = {
  componentConfig:  [
      {
        id: 0,
        name: "id",
        label: "Id",
        field_type: "number",
        fieldLength: 255,
        list_type: "",
        is_detail_link: true,
        is_group_by: false,
        is_inline_edit: true,
        is_hidden: false,
        is_search: true,
        is_click_to_call: false,
        is_email_field: false,
        is_currency_field: false,
        is_sales_rep: false,
        isRequired: false,
        is_phone_field: false,
        is_lookup_field: false,
        lookup_table_id: 0,
        lookup_field_id: 0,
        width: 50,
        is_relationship_field: false,
      },
      {
        id: 1,
        name: "componentName",
        label: "Component Name",
        field_type: "text",
        fieldLength: 128,
        list_type: "",
        is_detail_link: false,
        is_group_by: false,
        is_inline_edit: true,
        is_hidden: false,
        is_search: true,
        is_click_to_call: false,
        is_email_field: false,
        is_currency_field: false,
        is_sales_rep: false,
        isRequired: false,
        is_phone_field: false,
        is_lookup_field: false,
        lookup_table_id: 0,
        lookup_field_id: 0,
        width: 200,
        is_relationship_field: false,
      },
      {
        id: 2,
        name: "label",
        label: "Label",
        field_type: "text",
        fieldLength: 128,
        list_type: "",
        is_detail_link: false,
        is_group_by: false,
        is_inline_edit: true,
        is_hidden: false,
        is_search: true,
        is_click_to_call: false,
        is_email_field: false,
        is_currency_field: false,
        is_sales_rep: false,
        isRequired: false,
        is_phone_field: false,
        is_lookup_field: false,
        lookup_table_id: 0,
        lookup_field_id: 0,
        width: 200,
        is_relationship_field: false,
      },
    ],
  instituteSaveForm: [
    {
      id: 0,
      name: "id",
      label: "id",
      type: "number",
      fieldLength: 222,
      isHidden: true,
      isRequired: false,
      isSystemField: true,
      isReadonly: false,
      defaultValue: "",
      isEmailField: false,
      isPhoneField: false,
      isUrlField: false,
      isCurrencyField: false,
      optionList: [],
      grid: "12",
    },
    {
      id: 1,
      name: "name",
      label: "Institute Name",
      type: "text",
      fieldLength: 222,
      isHidden: false,
      isRequired: false,
      isSystemField: false,
      isReadonly: false,
      defaultValue: "",
      isEmailField: false,
      isPhoneField: false,
      isUrlField: false,
      isCurrencyField: false,
      optionList: [],
      grid: "12",
    },
    {
      id: 2,
      name: "location",
      label: "Location",
      type: "text",
      fieldLength: 222,
      isHidden: false,
      isRequired: false,
      isSystemField: false,
      isReadonly: false,
      defaultValue: "",
      isEmailField: false,
      isPhoneField: false,
      isUrlField: false,
      isCurrencyField: false,
      optionList: [],
      grid: "12",
    },
    {
      id: 3,
      name: "group",
      label: "Institute Group",
      type: "text",
      fieldLength: 222,
      isHidden: false,
      isRequired: false,
      isSystemField: false,
      isReadonly: false,
      defaultValue: "",
      isEmailField: false,
      isPhoneField: false,
      isUrlField: false,
      isCurrencyField: false,
      optionList: [],
      grid: "12",
    },
    {
      id: 4,
      name: "active",
      label: "Is Active",
      type: "check-box",
      fieldLength: 222,
      isHidden: false,
      isRequired: false,
      isSystemField: false,
      isReadonly: false,
      defaultValue: true,
      isEmailField: false,
      isPhoneField: false,
      isUrlField: false,
      isCurrencyField: false,
      optionList: [],
      grid: "12",
    },
    {
      id: 5,
      name: "internal",
      label: "Is Internal",
      type: "check-box",
      fieldLength: 222,
      isHidden: false,
      isRequired: false,
      isSystemField: false,
      isReadonly: false,
      defaultValue: false,
      isEmailField: false,
      isPhoneField: false,
      isUrlField: false,
      isCurrencyField: false,
      optionList: [],
      grid: "12",
    },
  ],
  instituteAdminForm: [
    {
      id: 0,
      name: "id",
      label: "id",
      type: "number",
      fieldLength: 222,
      isHidden: true,
      isRequired: false,
      isSystemField: true,
      isReadonly: false,
      defaultValue: "",
      isEmailField: false,
      isPhoneField: false,
      isUrlField: false,
      isCurrencyField: false,
      optionList: [],
      grid: "12",
    },
    {
      id: 1,
      name: "instituteId",
      label: "Institute Id",
      type: "number",
      fieldLength: 222,
      isHidden: true,
      isRequired: false,
      isSystemField: true,
      isReadonly: false,
      defaultValue: "",
      isEmailField: false,
      isPhoneField: false,
      isUrlField: false,
      isCurrencyField: false,
      optionList: [],
      grid: "12",
    },
    {
      id: 2,
      name: "fullName",
      label: "Contact Name",
      type: "text",
      fieldLength: 222,
      isHidden: false,
      isRequired: false,
      isSystemField: false,
      isReadonly: false,
      defaultValue: "",
      isEmailField: false,
      isPhoneField: false,
      isUrlField: false,
      isCurrencyField: false,
      optionList: [],
      grid: "12",
    },
    {
      id: 3,
      name: "email",
      label: "Email",
      type: "text",
      fieldLength: 222,
      isHidden: false,
      isRequired: false,
      isSystemField: false,
      isReadonly: false,
      defaultValue: "",
      isEmailField: true,
      isPhoneField: false,
      isUrlField: false,
      isCurrencyField: false,
      optionList: [],
      grid: "12",
    },
    {
      id: 4,
      name: "phoneNumber",
      label: "Contact No",
      type: "text",
      fieldLength: 222,
      isHidden: false,
      isRequired: false,
      isSystemField: false,
      isReadonly: false,
      defaultValue: "",
      isEmailField: false,
      isPhoneField: true,
      isUrlField: false,
      isCurrencyField: false,
      optionList: [],
      grid: "12",
    },
    {
      id: 5,
      name: "password",
      label: "Password",
      type: "text",
      fieldLength: 222,
      isHidden: false,
      isRequired: false,
      isSystemField: false,
      isReadonly: false,
      defaultValue: "",
      isEmailField: false,
      isPhoneField: true,
      isUrlField: false,
      isCurrencyField: false,
      optionList: [],
      grid: "12",
    },
  ],
  
  statusCode: {
    OK: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    NOT_IMPLEMENTED: 501,
  },
  sizeArr: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  typeArr: [
    "header",
    "text",
    "select",
    "check-box",
    "url",
    "date",
    "datetime",
    "number",
    "multi-select",
    "textarea",
    "editor",
    "code",
    "html",
  ],
};

export const {
  componentConfig,
  statusCode,
  instituteAdminForm,
  instituteSaveForm,
  sizeArr,
  typeArr,
} = globalConst;
